http_port 3128 accel defaultsite=lb01.infra.internal vhost

cache_peer 10.1.1.10 parent 80 0 no-query no-digest round-robin name=web01 originserver connect-timeout=2 connect-fail-limit=2
cache_peer 10.1.1.11 parent 80 0 no-query no-digest round-robin name=web02 originserver connect-timeout=2 connect-fail-limit=2

http_access allow all
via off
forwarded_for on

cache_mem 256 MB
cache_dir ufs /var/spool/squid 100 16 256
maximum_object_size 10 MB

access_log daemon:/var/log/squid/access.log squid